version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  dupl:
    threshold: 100
  gocognit:
    min-complexity: 20
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  goimports:
    local-prefixes: github.com/elaunira/openbao-plugin-database-clickhouse
  gosec:
    excludes:
      - G404 # Weak random number generator
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocognit
